name: 'GitHub Actions Message Bot'
 
on:
  push:
  schedule:
  # 定时任务
   # - cron: '0 11 ? 1-12 6/6'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    # 首先copy git仓库到虚拟机上
      - name: 'Checkout codes'
        uses: actions/checkout@v1
    # 执行仓库中的脚本文件
      - name: 'request_wechat_notify'
        run: bash ./work_wechat.sh
